version: "3"
services:
  bd:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=database-postgresql
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    ports:
      - 5432:5432